### PR TITLE
Fixing issues #161 and #163

### PR DESCRIPTION
**Pull request by vladonemo**
This contains fix for the two issues causing StackOverflowException when using DefaultValue.Mock.
The idea of the fix is the following:
* SetupAllProperties avoids loops in the graph of the properties. For example, if a mocked type contains a property of the same type, then this property is mocked with default value (null for reference types) instead. In fact, this was already addressed, but only in the direct child level.
* The test from issue #163 was failing even after the fix due to the fact, that some of the .NET framework types do not implement ISerializable properly (e.g. System.Reflection.Module, System.Reflection.Assembly). So in practice, you are not able to mock IFoo with DefaultValue.Mock if the IFoo contains a property of type Assembly (or Module, or even Type) anywhere in the property graph, because Castle throws ArgumentException. To fix this one I introduced IsSerialiableMockable extension method and use it in the SetupAllProperties (via SerializableTypesValueProvider decorator)

### CODE REVIEW

**Comment by kzu** [comment]
Could you fix the conflicts by rebasing on master so I can take another look at merging it?

Thanks!

**Comment by vladonemo** [comment]
should be ok now, thanks.

**Comment by kzu** [comment]
Hi @vladonemo sorry I broke again the merge-ability :(

I do see a large amount of changes that are just whitespace changes. Please make sure you have the EditorConfig VS extension and auto-format again from VS the files, all whitespace changes should be gone after that since the repo (master) now contains an .editorconfig file with the right settings.

Let me know if that works, thanks!

**Comment by vladonemo** [comment]
I have rebased, but now the AppVeyor build fails. I can't build it locally either. Missing Castle in the references. Any idea why?

**Comment by kzu** [comment]
Castle reference should be fixed now, but another rebase is needed now :(

**Comment by vladonemo** [comment]
done. I had to fix the build error ince the XUnit was updated to v2. And removed one dummy file which I checked in by coincidence.

**Comment by kzu** [comment]
The whitespaces changes are still there :(.

Please make sure you have the EditorConfig VS extension and auto-format again from VS the files, all whitespace changes should be gone after that since the repo (master) now contains an .editorconfig file with the right settings.

**Comment by vladonemo** [comment]
oh, I'm sorry. I used different PC. I applied the EditorConfig rules now to all 6 files that I've touched. I hope it's fine now. I also have Resharper, so not sure whether it fights with its formatting rules ...

**Comment by kzu** [comment]
Looks good. I'm sorry you have to use R# ;)

Thanks!

**Pull request merged**
