### PR TITLE
Updating System.Threading.Tasks.Extensions to 4.5.4

### PR DESCRIPTION
**Pull request by JeffAshton**
Fix for issue https://github.com/moq/moq4/issues/1107

### CODE REVIEW

**Comment by stakx** [comment]
Thanks. I'd like to wait a little and see if they push another release of that library in the next few days; increasing the build number might have been a mistake that they're possibly going to fix. If they won't, I'll merge this.

**Comment by JeffAshton** [comment]
@stakx, so this strong version bump did not happen recently.  v4.5.3 was released on 7/9/2019, and v4.5.4 early 2020.

Up until now it's merely been an inconvenience.  Not many of the standard libraries depend on this package.  But with the release of net 5, consumers of this library's dependency `System.Runtime.CompilerServices.Unsafe` have been upgraded. For example, `System.Collections.Immutable` has a dependency chain back to the next strong version of `System.Runtime.CompilerServices.Unsafe`.

Do you have a sense of how long you want to wait?  I'm also surprised they didn't release a 5.0.0, but it looks like everything that was going to get updated had a few months of previews and RCs, but `System.Threading.Tasks.Extensions` has been quiet.

**Comment by stakx** [comment]
I was under the impression that this was a relatively recent change since we only just got a report about it now; but if it's been that way for a while, there's probably no point in waiting.

**Comment by JeffAshton** [comment]
> I was under the impression that this was a relatively recent change since we only just got a report about it now; but if it's been that way for a while, there's probably no point in waiting.

I'm surprised it never got updated.  Some packages above it did:

```
Microsoft.Bcl.AsyncInterfaces (5.0.0)
  -> System.Threading.Tasks.Extensions (4.5.4)
      -> System.Runtime.CompilerServices.Unsafe (4.5.3)
```

And there is a v5.0.0 of `System.Runtime.CompilerServices.Unsafe`, but `System.Threading.Tasks.Extensions` and `System.Memory` haven't been updated yet to consume it.

I think there is value in having a version of `Moq` that points at v4.5.4 of `System.Threading.Tasks.Extensions`, even if short lived, to help bridge this net5.0 gap.  Given examples like the one above and this one:

```
System.Collections.Immutable (5.0.0)
  -> System.Memory (4.5.4)
      -> System.Runtime.CompilerServices.Unsafe (4.5.3)
```

**Review by stakx — CHANGES_REQUESTED** [review]
Almost good to go. Could you please also add a changelog entry at the top of `CHANGELOG.md`:

```diff
The format is loosely based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/).


+## Unreleased
+
+#### Changed
+
+* Upgraded `System.Threading.Tasks.Extensions` dependency to version 4.5.4 (@JeffAshton, #1108)
+
+
 ## 4.15.1 (2020-11-10)
```

**Review by stakx — APPROVED** [review]

**Comment by stakx** [comment]
Let's do this! 🚀 :wink:

**Comment by JeffAshton** [comment]
Thanks @stakx for the quick turnaround.

**Pull request merged**
