### PR TITLE
Fix for issue #92: Can't setup protected methods with nullable parameters

### PR DESCRIPTION
**Pull request by RobSiklos**

### CODE REVIEW

**Comment by kzu** [comment]
Any chance you could add a new unit test that exercises this new behavior? It's looking great :)

**Comment by RobSiklos** [comment]
> Any chance you could add a new unit test that exercises this new behavior? It's looking great :)

@kzu Sure. Should I put it in `ProtectedMockFixture` or `IssueReportsFixture` ?

**Comment by kzu** [comment]
sorry @RobSiklos. `ProtectedMockFixture` should be fine. 

thanks a lot!

**Comment by RobSiklos** [comment]
@kzu Ok, unit test added - you should be able to merge now.

**Pull request merged**
